feature: implement basic feature set and CLI interface
kubewarden/kwctl pull request #13
Opened 2021-04-30 15:57 UTC by ereslibre

The interface looks as follows:

```
USAGE:
    kwctl <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    help        Prints this message or the help of the given subcommand(s)
    policies    Lists all downloaded policies
    pull        Pulls a Kubewarden policy from a given URI
    run         Runs a Kubewarden policy from a given URI
```

2021-04-30 15:58 UTC, ereslibre commented on Cargo.toml
> +policy-fetcher = { git = "https://github.com/kubewarden/policy-fetcher", branch = "refactor" }
This is not intended to be merged, this PR depends on the following PR's:

- https://github.com/kubewarden/policy-evaluator/pull/2
- https://github.com/kubewarden/policy-fetcher/pull/2

2021-05-01 07:30 UTC, flavio requested changes
I don't like the usage of the `~/.kubewarden` directory. Even by using the `shellexpand` crate I think we end up having something that is doing unexpected things on platforms like Windows and OSx. Also on Linux, I would argue that this approach goes against the XDG specification.

I did some quick searches and I found the [directories](https://crates.io/crates/directories) crate which seems to be doing what we need, in a cross platform way.

2021-05-01 07:30 UTC, flavio commented on src/main.rs
> +             (@arg ("sources-path"): default_value("~/.kubewarden/sources.yaml") --("sources-path") +takes_value "YAML file holding source information (https, registry insecure hosts, custom CA's...)
The default values are going to be invalid on Windows and OSX

2021-05-01 07:30 UTC, flavio commented on src/main.rs
> +             (@arg ("sources-path"): default_value("~/.kubewarden/sources.yaml") --("sources-path") +takes_value "YAML file holding source information (https, registry insecure hosts, custom CA's...)
The default values are going to be invalid on Windows and OSX

2021-05-03 22:01 UTC, merged